/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** ANS1 Sequence. */
export interface ASN1Sequence {
  type: string
}
/** ANS1 OID. */
export interface ASN1OID {
  type: 'oid'
  oid: string
}
/** ANS1 Set. */
export interface ASN1Set {
  type: 'set'
  name: ASN1OID
  value: string
}
/** ANS1 JS Context Tag. */
export interface ASN1ContextTag {
  type: 'context'
  value: number
  contains: any
}
/** ANS1 JS bitstring. */
export interface ASN1BitString {
  type: 'bitstring'
  value: Buffer
}
/** Helper to convert a JS bigint to a JS Buffer */
export function BigIntToBuffer(data: bigint): Buffer
/** Helper to convert a JS Buffer to a JS bigint */
export function BufferToBigInt(data: Buffer): bigint
/** Helper to convert a JS number to a JS BigInt */
export function IntegerToBigInt(data: number): bigint
/** Helper to convert a JS string to a JS BigInt */
export function StringToBigInt(data: string): bigint
/** Convert JS input into ASN1 BER encoded data. */
export function JStoASN1(
  data:
    | BigInt
    | bigint
    | number
    | Date
    | Buffer
    | ASN1OID
    | ASN1Set
    | ASN1ContextTag
    | ASN1BitString
    | string
    | boolean
    | any[]
    | null,
): Asn1Encoder
/** Convert ASN1 BER encoded data to JS native types. */
export function ASN1toJS(
  data: string | null | number[] | Buffer | ArrayBuffer,
):
  | BigInt
  | bigint
  | number
  | Date
  | Buffer
  | ASN1OID
  | ASN1Set
  | ASN1ContextTag
  | ASN1BitString
  | string
  | boolean
  | any[]
  | null
export type ASN1 = Asn1
/** Convert ASN1 BER encoded data to JS native types. */
export class Asn1 {
  /** Js constructor */
  constructor(data: string | null | number[] | Buffer | ArrayBuffer | Asn1Encoder)
  /** Create an instance of ANS1 from a buffer. */
  static fromBuffer(value: Buffer): Asn1
  /** Create an instance of ANS1 from Base64 encoded data. */
  static fromBase64(value: string): Asn1
  /** Create an instance of ANS1 from hex encoded data */
  static fromHex(value: string): Asn1
  /** Convert to an integer. */
  intoInteger(): number
  /** Convert to a JS big integer. */
  intoBigInt(): bigint
  /** Convert to a boolean. */
  intoBool(): boolean
  /** Convert to a string. */
  intoString(): string
  /** Convert to a date. */
  intoDate(): Date
  /** Convert to an byte array. */
  intoBytes(): Array<number>
  /** Convert to a buffer. */
  intoBuffer(): Buffer
  /** Convert to an OID object. */
  intoOid(): ASN1OID
  /** Convert to a JS ASN1BitString object. */
  intoBitString(): ASN1BitString
  /** Convert to an Set object. */
  intoSet(): ASN1Set
  /** Convert to an Context object. */
  intoContextTag(): ASN1ContextTag
  /** Convert a Sequence to an Array. */
  intoArray(): any[]
}
export type ASN1Iterator = Asn1Iterator
export class Asn1Iterator {
  len(): bigint
}
export type ASN1Encoder = Asn1Encoder
export class Asn1Encoder {
  /** Create a new ANS1toJS instance from ASN1 encoded data. */
  constructor(
    data:
      | BigInt
      | bigint
      | number
      | Date
      | Buffer
      | ASN1OID
      | ASN1Set
      | ASN1ContextTag
      | ASN1BitString
      | string
      | boolean
      | any[]
      | null,
  )
  /** Encode the ASN.1 data as an array buffer. */
  toBER(sizeOnly?: boolean | undefined | null): ArrayBuffer
}
