/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JavaScript Types */
export const enum JsType {
  Sequence = 0,
  Integer = 1,
  DateTime = 2,
  Null = 3,
  String = 4,
  Boolean = 5,
  Unknown = 6,
  Undefined = 7
}
/**
 * Convert JS input into ASN1 BER encoded data.
 *
 * See [`asn1_rs::asn1_types`]
 */
export function JStoASN1(data: unknown): Array<number>
export function ASN1toJS(data: unknown): unknown
export type ASN1toJS = Asn1
/** Convert ASN1 BER encoded data to JS native types. */
export class Asn1 {
  /** Create a new ANS1toJS instance from ASN1 encoded data. */
  constructor(data: Array<number>)
  /** Get the JsType of the encoded data. */
  get type(): JsType
  /** Create an instance of ANS1toJS from Base64 encoded data. */
  static fromBase64(value: string): this
  /** Create an instance of ANS1toJS from hex encoded data */
  static fromHex(value: string): this
  /** Convert to an integer. */
  intoInteger(): number
  /** Convert to a big integer. */
  intoBigInteger(): bigint
  /** Convert to a boolean. */
  intoBool(): boolean
  /** Convert to a string. */
  intoString(): string
  /** Convert to a date. */
  intoDate(): Date
  /** Convert to an array. */
  intoArray(): any
  /** Convert to a buffer. */
  intoBuffer(): Buffer
}
export type ASN1OID = Asn1Oid
/** ANS1 OID. */
export class Asn1Oid { }
